version: '3'

services:
  web:
    build:
      context: ./web
    ports:
      - '80:80'
    volumes:
      - ./web/src:/var/www/html
      - ./data/img:/data/img
      - ./data/csv:/data/csv
    environment:
      - secret=mbsd
    privileged: true
    restart: always
  mysql:
    image: mariadb:latest
    ports:
      - '0.0.0.0:3306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: 'ecsite'
      MYSQL_USER: 'mbsd'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - '0.0.0.0:5555:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always

  api:
    build:
      context: ./api
    ports:
      - '3000:3000'
    volumes:
      - ./api/src/:/data
    networks:
      default:
        aliases:
          - api.mbsdmarket2025.local
    restart: always
