<?php
return [
    "home"      => "ホーム",
    "search"    => "商品検索",
    "new_item"  => "新規出品",
    "login"     => "ログイン",
    "register"  => "新規登録",
    "logout"    => "ログアウト",
    "user_list" => "ユーザ一覧",
    "own_product_list" => "出品商品一覧",
    "send_mail" => "メール送信",
    "charge" => "ポイントチャージ",
    "account_setting" => "アカウント設定",
    
    #"lib_amount" => "所持金：",
    "lib_amount" => "所持ポイント",
    #"lib_yen" => "￥",
    "lib_yen" => "ポイント",

    "account_setting" => "アカウント設定",
    "account_msg001" => "アカウントの確認・更新をおこなうページです。",
    "account_loginid" => "ログインID",
    "account_name" => "名前",
    "account_changepass" => "パスワードの変更はこちらです。",
    "account_password" => "パスワード",
    "account_togglepass" => "表示する",
    "account_apply" => "変更",

    "account_changepass_err001" => "パスワードは4文字以上20文字以内で入力してください。",
    "account_changepass_msg001" => "変更内容に間違いないか確認したうえで、実行してください。",
    "account_changepass_apply" => "実行",
    "account_changepass_back" => "戻る",
    "account_changepass_msg002" => "パスワードの変更が成功しました。",
    "account_changepass_err002" => "パスワードの変更が失敗しました。",
    "account_changepass_err003" => "パスワードの変更が失敗しました。入力文字列を再確認してください。",
    "account_changepass_link" => "アカウント設定ぺージへ",
    "account_changesetting_err001" => "ログインIDは4文字以上20文字以内で入力してください。",
    "account_changesetting_err002" => "名前は4文字以上20文字以内で入力してください。",
    "account_changesetting_msg001" => "変更内容に間違いないか確認したうえで、実行してください。",
    "account_changesetting_apply" => "実行",
    "account_changesetting_back" => "戻る",
    "account_changesetting_err003" => "入力値エラー",
    "account_changesetting_err004" => "このログインIDは既に使用されています。",
    "account_changesetting_msg002" => "アカウント変更が成功しました。",
    "account_changesetting_err005" => "アカウント変更が失敗しました。",
    "account_changesetting_link" => "アカウント設定ぺージへ",

    "index_rcv_mail" => "受信メール",
    "index_snd_mail" => "送信メール",
    "index_purchases" => "購入品",
    "index_msg001" => "MBSD Marketにはこんな素敵な商品が様々なユーザから出品されています！",

    "login_error001" => "IDかパスワードが違います",
    "login_login" => "ログイン",
    "login_loginid" => "ログインID",
    "login_password" => "パスワード",
    "login_submit" => "ログイン",

    "register_err001" => "エラー",
    "register_back" => "戻る",
    "register_err002" => "IDに半角英数字および「-」、「_」、「.」「@」以外の文字は利用できません。",
    "register_err003" => "ログインIDは4文字以上20文字以内で入力してください。",
    "register_err004" => "パスワードは空にできません。",
    "register_err005" => "クレジットカード番号は正しい形式で入力してください。",
    "register_err006" => "既に登録されているIDです。",
    "register_err007" => "名前は空にできません。",
    "register_" => "",
    "register_" => "",
    "register_register" => "新規登録",
    "register_loginid" => "ログインID",
    "register_password" => "パスワード",
    "register_name" => "名前",
    "register_submit" => "登録",

    "product_showproduct_comment_err001" => "コメントが入力されていません。",
    "product_showproduct_comment_err002" => "商品タイトルは必須です。",
    "product_showproduct_comment_err003" => "ポイント数は必須です。",
    "product_showproduct_price" => "ポイント",
    "product_showproduct_seller" => "販売者",
    "product_showproduct_condition" => "状態",
    "product_showproduct_sell" => "販売中",
    "product_showproduct_soldout" => "売り切れ",
    "product_showproduct_edit" => "編集",
    "product_showproduct_editproduct" => "商品情報編集",
    "product_showproduct_noteditable" => "変更不可",
    "product_showproduct_productoverview" => "商品概要",
    "product_showproduct_comment" => "コメント",
    "product_showproduct_postcomment" => "コメント投稿",
    "product_showproduct_postplaceholder" => "コメント",
    "product_showproduct_submit" => "投稿",
    
    "product_showproducts_productname" => "商品名",
    "product_showproducts_searchproduct" => "商品名検索",

    "product_makeproduct_price" => "ポイント",
    "product_makeproduct_purchaserestriction" => "購入制限",
    "product_makeproduct_ristrictionlist" => "以下のリスト",
    "product_makeproduct_mutualfollowers" => "相互フォロワーのみ",
    "product_makeproduct_onlyfollowers" => "フォロワーのみ",
    "product_makeproduct_norestriction" => "制限なし",
    "product_makeproduct_eligiblebuyer" => "購入可能ユーザ",
    "product_makeproduct_productoverview" => "商品概要",
    "product_makeproduct_register" => "登録",
    "product_makeproduct_back" => "戻る",
    "product_makeproduct_registrationcomplete" => "商品登録が完了しました",
    "product_makeproduct_productname" => "商品名",
    "product_makeproduct_productimg" => "商品画像",
    "product_makeproduct_chooseimg" => "画像選択",
    "product_makeproduct_productprice" => "販売ポイント数",
    "product_makeproduct_selectfollower" => "フォローの中から指定",
    "product_makeproduct_specifyeligiblebuyer" => "購入対象ユーザ指定",
    "product_makeproduct_submit" => "確認画面へ",
    "product_makeproduct_uploadsizeerr001" => "アップロードするファイルは1MB以下にしてください",

    "product_ownproducts_sell" => "販売中",
    "product_ownproducts_soldout" => "売り切れ",
    "product_ownproducts_stopsale" => "販売中止",
    "product_ownproducts_norestriction" => "制限なし",
    "product_ownproducts_mutualfollowers" => "相互フォローのみ",
    "product_ownproducts_selectfollower" => "フォローの中から指定",
    "product_ownproducts_onlyfollowers" => "フォロワーのみ",
    "product_ownproducts_productname" => "商品名",
    "product_ownproducts_productoverview" => "商品説明",
    "product_ownproducts_productprice" => "販売ポイント数",
    "product_ownproducts_purchaserestriction" => "購入制限",
    "product_ownproducts_condition" => "状態",
    "product_ownproducts_makefileerr001" => "ファイルの作成に失敗しました。",
    "product_ownproducts_searchownproduct" => "出品商品検索",
    "product_ownproducts_msg001" => "あなたが出品している商品の一覧",
    "product_ownproducts_searchproduct" => "商品名検索",
    "product_ownproducts_csv" => "出品商品一覧CSV",
    "product_ownproducts_submitcsv" => "出品商品一覧をCSV出力",

    "product_buyProduct_success" => "購入に成功しました。",
    "product_buyProduct_fail" => "購入に失敗しました。",
    "product_buyProduct_back" => "商品検索に戻る",
    "product_buyProduct_price" => "ポイント",
    "product_buyProduct_seller" => "販売者",
    "product_buyProduct_state" => "状態",
    "product_buyProduct_available" => "購入可能",
    "product_buyProduct_productoverview" => "商品概要",
    "product_buyProduct_submit" => "購入する",

    "csvdl_err001" => " が見つかりません。",

    "userlist_userlist" => "ユーザ一覧",
    "userlist_usernameerr001" => "英数字で入力してください。",
    "userlist_follow" => "→　：フォローしている",
    "userlist_follower" => "←　：フォローされている",
    "userlist_mutualfollower" => "&#9829;　：相互フォロー",
    "userlist_me" => "●　：自分",
    "userlist_searchusername" => "ユーザ名検索",
    "userlist_message001" => "ユーザー名（英数字）の一部を入力してください。",

    "user_msg_follow" => " をフォローしました",
    "user_msg_unfollow" => " へのフォローを外しました",
    "user_name" => "名前",
    #"user_amount" => "所持金",
    "user_amount" => "所持ポイント",
    "user_follow" => "フォローする",
    "user_unfollow" => "フォローを外す",
    "user_mail_send" => "メール送信",
    "user_mail_title" => "タイトル",
    "user_mail_msg" => "メッセージ",
    "user_mail_submit" => "送信",
    "user_msg001" => "販売している商品一覧",

    "sendmail_msg_err001" => "件名・本文を入力してください。",
    "sendmail_msg_err002" => "メールが送信できませんでした。",
    "sendmail_msg_send" => " にメールを送信しました。",
    "sendmail_back" => "戻る",
    "sendmail_sendmail" => "メール送信",
    "sendmail_selectuser" => "送信先ユーザ名",
    "sendmail_nomutualfollowers" => "相互フォローユーザーがいません",
    "sendmail_title" => "件名",
    "sendmail_body" => "本文",
    "sendmail_submit" => "送信",

    "readmail_del_msg001" => "削除しました",
    "readmail_del_back" => "戻る",
    "readmail_title" => "件名",
    "readmail_from" => "送信者名",
    "readmail_to" => "受信者名",
    "readmail_rep_form" => "返信フォーム",
    "readmail_rep_title" => "件名",
    "readmail_rep_body" => "本文",
    "readmail_rep_submit" => "送信",
    "readmail_del_del" => "削除",
    "readmail_del_msg002" => "メールを削除しますか？",
    "readmail_del_submit" => "削除",

    "coupon_apply_msg001" => "クーポンコードを適用完了！ ",
    "coupon_apply_msg002" => " ポイントを追加しました。",
    "coupon_apply_err001" => "クーポンコードの使用に失敗しました。",
    "coupon_apply_err002" => "入力されたクーポンコードが存在しません。",
    "coupon_title" => "ポイントチャージ",
    "coupon_msg001" => "システムから発行されたクーポンコードを使用することで、ポイントをチャージできます。",
    "coupon_couponcode" => "クーポンコード： ",
    "coupon_help" => "※クーポンコードは管理者からご案内させていただきます。",
    "coupon_history001" => "チャージ履歴",
    "coupon_msg002" => "最大10件のみ最新のチャージ履歴を表示します",
    "coupon_id" => "ID",
    "coupon_date" => "チャージ日時",
    "coupon_amount" => "ポイント数",
    "coupon_history002" => "チャージ履歴はありません。",

    "admin_img_msg001" => "商品画像差し替え",
    "admin_img_id" => "商品ID",
    "admin_img_choose" => "Choose a file... ",
    "admin_userdel_msg001" => "ユーザ削除",
    "admin_userdel_id" => "ユーザID",
    "admin_coupon_msg001" => "クーポン管理",
    "admin_coupon_link001" => "ポイントクーポン発行ページへ",

    "admin_coupon_gen_msg001" => "クーポンコードを生成しました",
    "admin_coupon_gen_err001" => "ERROR: クーポンコードを生成できませんでした。",
    "admin_coupon_gen_err002" => "ERROR: 金額が無効な値です。",
    "admin_coupon_gen_link001" => "ポイントクーポン発行ページへ",
    #"admin_coupon_gen_amount" => "金額",
    "admin_coupon_gen_amount" => "ポイント数",
    "admin_coupon_gen_submit" => "発行",
    "admin_coupon_gen_msg002" => "最大10件のみ未使用のクーポンコードを表示します。",
    "admin_coupon_gen_id" => "ID",
    "admin_coupon_gen_createat" => "作成日時",
    "admin_coupon_gen_code" => "コード（共有リンク）",
    "admin_coupon_gen_msg003" => "利用可能なクーポンはありません。",

];
# <?php echo $lang[""]; ?>
